package edu.cs401group3.crm.commands;

public enum Commands {
	ADD_USER, DELETE_USER, EDIT_USER,
	ADD_CLIENT, DELETE_CLIENT, EDIT_CLIENT,
	ADD_RECORD, DELETE_RECORD, EDIT_RECORD,
	ADD_GROUP, DELETE_GROUP, EDIT_GROUP,
	IMPORT, EXPORT, SAVE, DUMMY_COMMAND
}
